services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-webhook-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./tmp:/usr/src/app/tmp
